# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 18, 35, 43, 309922)),
        ),
    ]
