# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160318_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='instances',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
