# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='instances',
        ),
    ]
