# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_tag_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='percent',
            field=models.CharField(default='50', max_length=3),
            preserve_default=False,
        ),
    ]
